# -*- coding: utf-8 -*-
# Lotto 78: chiusura di *chat_default in chat.hsp.
# Accenti VERI: e' `applica` a degradarli in build (Shift-JIS).
RESE = {
 19887: "Con i criminali non faccio affari.",
 19238: "Ricevere l'ospite",
 19239: "Non ricevere nessuno",
 20810: "Ecco la tua consegna!",
 20811: "Scusa.",
 20812: '"Ma è uno scherzo? Quel che hai in mano non è il pezzo su misura che avevo ordinato: " + ioriginalnameref(inv(INV_ITEM_ID, deliver(1))) + "..."',
 20817: "E va bene, lascia stare.",
 20837: '"Consegni " + itemname(deliver(1), 1) + "."',
 20854: '"Consegni " + itemname(supply, 1) + "."',
 20867: "Maledizione, un altro bandito che mi rovina gli affari! Mercenari, in formazione!",
 20868: "Prega il tuo dio.",
 20869: "A-aspetta! Stavo scherzando!",
 20881: "Ci vuole depredare! Mercenari, in formazione!",
 20889: "Ehi, ma che fai!?",
 20892: "Hai affondato una nave mercantile.",
 20894: "Ci affondi così, di punto in bianco, senza nemmeno saccheggiare? Sei fuori di testa!",
 21386: '"Tu, " + cdatan(CDATAN_NAME, tc) + " e " + cdatan(CDATAN_NAME, ttc) + " entrate in un mondo tutto vostro."',
 21417: '"Tu e " + cdatan(CDATAN_NAME, tc) + " entrate in un mondo tutto vostro."',
 21447: '"Tu e " + cdatan(CDATAN_NAME, tc) + " entrate in un mondo tutto vostro."',
 22405: 'cdatan(CDATAN_NAME, cnt) + " dice: " + cnvtalk("Non lo permetterò!")',
 22412: '"(" + name(tc) + " rifiuta con garbo la tua proposta.)"',
 22416: "Sì... con gioia.",
 22431: "In questa modalità di gioco non si possono lasciare geni.",
 22435: "Non qui!",
 22438: "*arrossisce*",
 22447: 'cdatan(CDATAN_NAME, cnt) + " dice: " + cnvtalk("Smettila subito! Non vedi che Jure non ne vuole sapere?!")',
 22725: "......",
 23050: "(Dividono il pasto...)",
 23052: "(*gnam gnam*)",
 23068: "Però, che bontà!",
 23071: "Era proprio buono!",
 23079: "Squisito, davvero squisito!",
 23082: "Roba da settimo cielo!",
 23142: "(Avete diviso il pasto fatto in casa, in buona compagnia...)",
 23160: "Però, che bontà!",
 23358: "Facciamolo",
 23359: "Annulla",
 23360: "Sei... niente male. Ti compro.",
 23379: "Va bene.",
 23389: '"D\'accordo, tesoro: mi servono " + sexvalue + " monete d\'oro in anticipo."',
 23415: "Annulla",
 23420: "(Il capo della carovana sembra occupato e non si accorge di te. Se ti infili adesso tra le casse, forse riesci a passare il confine. Verso dove?)",
 23449: "(Il capo della carovana, che si annoiava, incrocia il tuo sguardo.)",
 23450: "Oh? Vuoi uscire dal paese? Purtroppo non si può: il confine è bloccato e passano solo i pezzi grossi. Aspetto qui ogni giorno perché, appena il blocco si allenta, devo portare via subito questi mercanti.",
 23451: "Anche se il blocco venisse tolto per un po', gli avventurieri non passerebbero. Un mercante lo porterei volentieri a Tyris del Sud, ma non chi va all'avventura: ho paura che ci rubi il carico.",
 23480: "Tutto qui? ...Va bene. Mi prendo una moneta di bronzo per il disturbo.",
 23493: "Bene. Scrivi il numero del progetto che devo seguire.",
 23494: '" (Numero del disegno nella cartella user\\item, da 1 a 33. Dal 21 al 33 sono di misura 48*96. Con 0 si torna all\'originale.) "',
 23509: "Riporti l'oggetto all'aspetto originale.",
 23659: "Ecco fatto.",
 23669: "Non ne hai abbastanza!",
 23844: "(Salire a bordo)",
 23845: "Aspetta.",
 23846: "Questa lettera di presentazione... Ah, ho capito. Sali a bordo, si salpa subito.",
 13591: "Andiamo.",
 13592: "Si parte?",
 10879: "Leggimi la sfortuna",
 24774: "E il mio incarico? Va tutto bene?",
 24780: "Accetto l'incarico",
 24781: "Annulla",
 24795: "Ehi, hai parecchi incarichi ancora aperti. Torna a cercarmi quando li hai chiusi.",
 24813: "Sembra che il tuo zaino sia già pieno. Torna a cercarmi quando hai fatto ordine.",
 24861: "Grazie. Conto su di te.",
 24873: '"Hai messo " + itemname(ci, 1) + " nello zaino."',
 24876: "Ecco il pacco. Occhio alla scadenza: non vorrei doverti denunciare alle guardie.",
 24886: "Benissimo! Ti accompagno sul posto: sterminali tutti!",
 24889: "D'accordo. Ti porto al mio campo.",
 24892: "Seguimi, ti prego. Non vorrei che finissi su una trappola e ci lasciassi la pelle.",
 24895: "Va bene, ti porto subito alla festa.",
 24919: "Torna a cercarmi quando ti serve altro allenamento.",
 24935: "Non hai abbastanza monete di platino.",
 24969: "Ottimo lavoro. Hai più margine di crescita di chiunque altro abbia mai allenato. Continua ad allenarti.",
 24988: "Ti ho insegnato tutto quello che so di questa abilità. Adesso tocca a te allenarla.",
 24998: '"Oh, vuoi investire nel mio negozio? Ti costa " + calcinvestvalue() + " monete d\'oro. Spero che tu le abbia."',
 25000: '"Investire (" + calcinvestvalue() + strgold + ")"',
 25003: '"Investire 50 (" + calcinvestvalue50() + strgold + ")"',
 25005: "Annulla",
 25029: 'cdatan(CDATAN_NAME, tc) + " ti è riconoscente..."',
 25053: 'cdatan(CDATAN_NAME, tc) + " ti è molto riconoscente!"',
}
# le due firme che condividono la riga 23366: si distinguono per inglese
PER_EN = {
 "Okay, no turning back now!": "E allora andiamo, non si torna indietro!",
 "Come on!": "Su, dai!",
}
