# -*- coding: utf-8 -*-
# Lotto 78c: l'INIZIO della storia - Larnneire, Rianna, Lomias e il TUTORIAL.
# I nomi dell'interfaccia si copiano da text.hsp: Mangia, Leggi, Scava,
# Equipaggia, Tiro, Raccogli, Posa. Diario, zaino, pergamena di
# identificazione / di purificazione, lingotto d'oro, grimaldello,
# bacheca della casa, baule degli stipendi, Tyris del Nord, Irva Perduta.
RESE = {
 # --- Larnneire, la ascoltatrice del vento -------------------------------
 1591: "Bethel...",
 1595: "Vederti qui mi ha sorpreso, ma a pensarci bene non è poi così strano incontrare chi va all'avventura a Irva Perduta.",
 1598: '"Ma tu sei... " + cdatan(CDATAN_NAME, CHARA_PLAYER) + "?"',
 1599: "Perdonami, guardavo altrove e non ti avevo riconosciuto. Sono felice di rivederti: non ci vedevamo da quando studiavamo i Meshera col Melugast.",
 1600: "Da allora ci siamo dati da fare per far rinascere la Foresta Eretica, e siamo venuti fin qui a cercare Bethel. Se lo incontri, torna a dircelo.",
 1606: "Qual è il vostro scopo?",
 1607: "Parlami di Tyris del Nord.",
 1608: "Hai accennato a una favola.",
 1610: "Sono contenta che tu sia di nuovo in forze. All'inizio pensavo che non ci fosse più niente da fare.",
 1613: "Forse questa storia l'hai già sentita...",
 1614: "C'era una volta un principe che una strega trasformò in una bestia orribile. Disperato per il proprio aspetto, si nascose in una foresta lontana dal suo regno.",
 1615: "Un giorno una donna, ferita gravemente da un branco di lupi, si rifugiò nella sua capanna e svenne. Lui la curò, sapendo e temendo che il suo corpo mostruoso l'avrebbe spaventata. E così fu: appena si svegliò, lei gridò.",
 1616: "Ma con il passare dei giorni, mentre riprendeva le forze, la donna riconobbe la gentilezza e la generosità che stavano nel cuore di quella bestia. E decise di restare a vivere con lui.",
 1617: "Insieme superarono molte difficoltà, e la storia finisce quando la maledizione si spezza e la bestia torna quello che era: un principe di bellezza perfetta. Da allora i due vissero in armonia. Un lieto fine... una storia come tante, non trovi?",
 1618: "Gli anziani di Vindale me la raccontavano spesso, questa storia. Ma non mi è mai piaciuta. Forse perché mi sembrava che l'amore per la bestia fosse rimasto indietro da qualche parte, insieme alla sua bruttezza.",
 1622: "Tyris del Nord è un continente nell'emisfero occidentale di Irva. Mercanti e viaggiatori a non finire mettono piede su questa terra, e sognano di far fortuna nelle antiche rovine delle Nefie.",
 1623: "Se non hai ancora deciso dove andare, ti conviene passare da Vernis: è una città mineraria, a sud di qui.",
 1627: "Siamo messaggeri di Vindale. Il nostro viaggio finisce qui a Tyris del Nord, nella grande città di Palmia, dove dobbiamo parlare con re Xabi, un uomo giusto e compassionevole.",

 # --- Rianna, la sognatrice ----------------------------------------------
 1636: "Bethel! Bethel! Bethel! Betheeeeeeeeeeel! ! ! Ah ah ah... ah... Aaaaah! Aaaaaaah!!! Be-thel-be-thel-be-theeeeel!!! Il Bethel che mi immagino è troppo bello!! Aaaah... ah... Aaaaaah!! Fiiiiih!! Oh oh oh oh! Che bello! Bethel! Che bello! Sono felice di vederti anche solo in sogno... Uaaah... ah ah ah!!! Aaaaaaaah!! Guaaa ah ah ah ah!!! Il sogno non è la realtà!!!! Ah... ma se ci pensi bene, fra sogni e fantasie... beh, non è forse una fantasia anche che tu mi abbia sempre amata? Gnaaa ah ah ah ah aaan!! Uaa ah ah ah!! Iiiiih ah ah ah!! Haaaaaaaa!! Basta! Maledizione! Rinuncio!! Rinuncio alla realtà!!",
 1639: "Ma insomma! È un'eternità che aspettiamo Bethel!",

 # --- Lomias, fuori dal tutorial -----------------------------------------
 1649: "Uff. A quanto pare qui io sono di troppo. Comunque, quando ha intenzione di tornare nella foresta, Larnneire?",
 1652: "Eh... si aspetta che quello scemo di Bethel torni dalla sua avventura.",
 1653: "Eh? Chiunque tu sia, lasciami in pace...",
 1659: "...Sei di nuovo in piedi? Il tempo vola. È ora che ci mettiamo in cammino anche noi.",
 1661: '"Non fare quella faccia, " + cdatan(CDATAN_NAME, CHARA_PLAYER) + ". Abbiamo cose da fare in questo paese: sono certa che ci rivedremo."',
 1664: "Hai ottenuto un vecchio talismano! Gli oggetti delle missioni si controllano nel diario (tasto j).",
 1668: "Ecco... tieni questo amuleto. Un giorno potrebbe servirti.",
 1671: "Nemmeno noi abbiamo molto da dare, ma ti lasciamo qualche oggetto che può tornare utile. Abbiamo interrotto il viaggio per tirare qualcuno fuori dai guai: sarebbe un peccato che finisse per crepare in un fosso.",
 1674: '"...e allora, fino al giorno in cui ci ritroveremo, " + cdatan(CDATAN_NAME, CHARA_PLAYER) + ", che i venti di Lulwy ti proteggano."',
 1679: "Lomias e Larnneire raccolgono le loro cose e lasciano la caverna.",
 1799: "Verme che non sei altro!",
 1803: 'name(tc) + " va su tutte le furie!"',
 1810: 'cdatan(CDATAN_NAME, CHARA_PLAYER) + " ha ragione. Ci resta poco tempo. Dobbiamo partire, Lomias."',
 1811: "Sì. Palmia è ancora lontana. Forse è stata una fortuna poterci riposare un poco, prima che cominci tutto.",
 1812: "Non è molto, ma ti lasciamo qualche oggetto che può servirti. Addio... fino al giorno in cui ci ritroveremo. Che la benedizione di Lulwy sia con te.",
 1815: "Lomias e Larnneire lasciano la caverna.",

 # --- il TUTORIAL --------------------------------------------------------
 1703: "A quanto vedo non sei di queste parti. Se non ti offendi, prima di ripartire ho il tempo di insegnarti qualche regola di sopravvivenza.",
 1704: "Voglio fare il tutorial",
 1705: "Non serve, grazie",
 1786: "Scelta saggia. Cominciamo dalle cose più semplici.",
 1708: "Almeno muoverti saprai. I tasti freccia bastano, ma se hai un tastierino numerico è meglio usare quello: lì intorno hai i tasti che servono di più, lo 0 per raccogliere da terra, il 5 per passare il turno e l'asterisco per scegliere il bersaglio.",
 1709: "Le azioni che puoi fare sono tante, ma in fondo ci arrivi tutte con tre soli tasti: z, x e c.",
 1710: "Proviamoli subito. Per prima cosa, per vivere serve mangiare. Se lo stomaco è vuoto perdi HP e ti muovi più lentamente. Tieni sempre da parte qualcosa da mangiare.",
 1711: "Tieni, questa carne è tua. Premi x, poi premi 9 un paio di volte per arrivare al menu <Mangia>. Da lì scegli la carne che è per terra.",
 1712: "Va bene",
 1713: "Ho mangiato",
 1837: "Ehm... l'hai mangiata davvero? Vabbè...",
 1838: "Anche gli altri oggetti si usano col tasto x. Per esempio, se vuoi leggere un libro premi x, poi 9 un paio di volte fino al menu <Leggi>, e scegli il libro.",
 1839: "Gli oggetti per terra li raccogli col tasto g, e quelli che hai addosso li posi col tasto d. C'è un limite al peso che puoi portare, quindi conviene non girare con roba che usi di rado.",
 1840: "Adesso ti spiego che cosa fa il tasto z.",
 1716: "Col tasto z puoi usare abilità e altre azioni, come sfondare e scavare. Un consiglio: sfondando apri le porte chiuse a chiave e fai cadere la frutta dagli alberi. Serve anche a svegliare qualcuno, ma non la prenderà bene.",
 1717: "E ricordati della barra spaziatrice: è un tasto molto comodo. Quando hai qualcosa sotto i piedi, sceglie da sola l'azione giusta.",
 1718: "Proviamo subito. Scava un muro: premi z e scegli <Scava>.",
 1719: "Va bene",
 1726: "A quanto pare hai trovato qualcosa.",
 1730: "Di molti oggetti, per sapere che cosa sono davvero, serve l'identificazione. Puoi identificarli leggendo certe pergamene o chiedendo a un mago in città. Ricorda che usare pozioni e pergamene non identificate è molto pericoloso.",
 1731: "Anche armi e armature vanno identificate. Se le porti addosso abbastanza a lungo ti fai un'idea di quanto valgono, ma per conoscerle davvero serve l'identificazione.",
 1732: "Ecco una pergamena di identificazione. Leggila col tasto x e identifica il lingotto d'oro che hai trovato.",
 1733: "D'accordo, provo",
 1734: "Fatto...",
 1845: "(Lomias sogghigna: il lingotto falso l'ha sotterrato lui.)",
 1846: "Bene, adesso ti spiego come si combatte. Prima di cominciare devi equipaggiarti. Prendi il mio vecchio arco e le frecce, e mettili addosso.",
 1737: "Per indossare armi e armature premi c e poi 9 fino a <Equipaggia>. Attenzione: se indossi qualcosa di maledetto non riesci più a toglierlo, e ti porta effetti sgradevoli. Quell'arco è maledetto: usa questa pergamena di purificazione.",
 1738: "Va bene",
 1739: "Fatto tutto",
 1862: "...Bene, si arriva al combattimento.",
 1863: "Per colpire qualcuno con un'arma da mischia basta che tu vada verso di lui. Per l'arma a distanza puoi premere z e scegliere Tiro, oppure premere f (Fire): colpisci il nemico più vicino. Se vuoi cambiare bersaglio, premi l'asterisco.",
 1864: "Preparati. Adesso ti chiamo qualche mostro debole. Se puoi, abbattili con l'arco: da vicino l'arco vale poco, quindi tieniti a distanza. Ti lascio per terra qualche pozione, se ti fai male. Sai come si usano, no?... Sì, col tasto x.",
 1866: "Lomias libera il putit che teneva nascosto.",
 1744: "Che aspetti? Il putit è ancora in piedi.",
 1747: "Ottimo.",
 1751: "Un po' di storia di Tyris del Nord. Terra sacra governata da Palmia, è famosa per le antiche rovine chiamate <<Nefia>>. Ogni tanto i movimenti della crosta ne fanno nascere di nuove, e ne cancellano altre.",
 1752: "Nel piano più profondo di queste rovine vive un signore che custodisce grandi tesori, e per questo gli avventurieri accorrono a frotte. Ma stai alla larga dalle rovine che superano il tuo livello: puoi guadagnarci molto, e puoi rimetterci la vita.",
 1759: "Nelle rovine puoi trovare bauli pieni di roba. Ce n'è uno qui vicino: aprilo.",
 1764: "Vedi che il baule ha una serratura? Per aprirlo servono i grimaldelli e abbastanza abilità nello Scasso. Ti tocca esercitarti. E ricorda: i bauli pesano, quindi se in un sotterraneo non riesci ad aprirlo, lascialo dov'è. Ho visto uno scemo girare con un baule in spalla, e ci ha rimesso la pelle.",
 1765: "Più esplori i sotterranei, più lo zaino si appesantisce. Quello che non ti serve lascialo a casa: portarsi dietro troppo peso rallenta i movimenti.",
 1766: "Per finire, due parole sulla casa. Come sai, in casa puoi tenere gli oggetti al sicuro. E ogni tanto il baule degli stipendi si riempie di oro e di roba. Prima o poi potrai comprarne una nuova.",
 1767: "Con la bacheca della casa puoi fare parecchie cose. Provala con calma, più avanti.",
 1771: "Bene, abbiamo finito. Ormai dovresti sapere come si sopravvive a Tyris del Nord.",
 1772: "(Tutorial finito!)",
 1777: "Ti serve altro?",
 1778: "Niente",
 1781: "Non è ora che partiate per Palmia?",

 # --- le otto sorelle di «Va bene», in menu lontani -----------------------
 9576: "Stavolta non scappare",
 9589: "Chi sei, scusa?",
 10672: "Non capisco",
 11829: "(Allontanarsi)",
 11831: "Non voglio andarci",
 15185: "Fammi pensare",
 2211: "Le navi le detesto",
 2216: "Non salgo mai più su una nave",
}
# la seconda firma della riga 1837, distinta per inglese
PER_EN = {
 "What!": "Ma dai!",
}
