# -*- coding: utf-8 -*-
"""Le rese dei nomi NON IDENTIFICATI di db_item.hsp (83a sessione).

Chiave: (giapponese, inglese) -> (italiano, plurale, genere).
La chiave e' la coppia perche' e' quella che fa la firma: «tonfa» sta su
cinque oggetti con cinque giapponesi diversi, «deity of Irva» su due.

⭐⭐⭐ Le rese sono di DUE tipi, e il tipo non si sceglie: si misura.

- **201 firme** stanno su oggetti **semplici** (`ioriginalnameref2` vuoto): li'
  il nome non identificato e' tutto il nome, e la resa e' un sostantivo con
  l'articolo suo — «degli artigli robusti», «un liquido trasparente».
- **21 firme** stanno su oggetti **composti**, e su TUTTI i loro oggetti: li' il
  gioco scrive la parola-contatore anche quando l'oggetto non e' identificato
  (`item_func.hsp:1217`, `:1259`), e la resa e' un **complemento dopo «di»** —
  «una statua di divinita' di Irva», «una pozione superiore di sofferenza
  inflitta», «una gemma gialla di poteri divini».
- **2 firme** sono miste e la resa deve reggere tutt'e due i telai: «carta
  sbrindellata» sta bene sia da sola sia dopo «gettone di».

⚠️ Quelle 21 sono esattamente gli inglesi che a prima lettura sembravano
astrazioni sciatte — «godly powers», «unknown content», «a fishy figure»,
«blue color», «inflicting suffering». Non lo sono: **e' il ruolo grammaticale
che non avevo misurato.** «a statue of deity of Irva» e' inglese giusto, e
«statua di divinita' di Irva» e' italiano giusto. La prima stesura le aveva
rese come nomi pieni — «statua di divinita'», «gemma divina» — e il gioco
avrebbe scritto «una statua di statua di divinita'».
"""
RESE = {
 ("大熊の剛爪", "strong claws"): ("artigli robusti", "artigli robusti", "mp"),
 ("虐殺ウィッグ", "changing side-tail wig"): ("parrucca mutevole a codino", "parrucche mutevoli a codino", "f"),
 ("防御ウィッグ", "changing wig"): ("parrucca mutevole", "parrucche mutevoli", "f"),
 ("鋭利な骨", "sharp bone"): ("osso affilato", "ossi affilati", "m"),
 ("金色の葉っぱ", "golden leave"): ("foglia dorata", "foglie dorate", "f"),
 ("古き紙々", "ancient papers"): ("carte antiche", "carte antiche", "fp"),
 ("苦しみを呼ぶ薬", "inflicting suffering"): ("sofferenza inflitta", "sofferenze inflitte", "f"),
 ("呪いを呼ぶ薬", "inflicting curse"): ("maledizione inflitta", "maledizioni inflitte", "f"),
 ("災いを呼ぶ薬", "inflicting misfortune"): ("sventura inflitta", "sventure inflitte", "f"),
 ("新式の薬", "novelty"): ("foggia nuova", "fogge nuove", "f"),
 ("古の薬", "ancient origins"): ("origini antiche", "origini antiche", "fp"),
 ("複雑な部品", "intricate component"): ("componente intricato", "componenti intricati", "m"),
 ("ねばねば", "sticky blob"): ("massa appiccicosa", "masse appiccicose", "f"),
 ("死体パーツ", "necro parts"): ("pezzi di cadavere", "pezzi di cadavere", "mp"),
 ("おぞましき本", "unknown origins"): ("origini ignote", "origini ignote", "fp"),
 ("力強い結晶体", "powerful fragment"): ("frammento possente", "frammenti possenti", "m"),
 ("黄金の指", "golden finger"): ("dito dorato", "dita dorate", "m"),
 ("謎のプログラム", "photon program"): ("programma misterioso", "programmi misteriosi", "m"),
 ("立派な勲章", "respectable medal"): ("medaglia ragguardevole", "medaglie ragguardevoli", "f"),
 ("神々しい文書", "divine proof"): ("documento divino", "documenti divini", "m"),
 ("謎の機械", "unknown functionailties"): ("funzioni ignote", "funzioni ignote", "fp"),
 ("うつろう制服", "changing uniform"): ("uniforme mutevole", "uniformi mutevoli", "f"),
 ("竹のアーマー", "bamboo armor"): ("armatura di bambù", "armature di bambù", "f"),
 ("黒き混沌の剣", "chaotic sword"): ("spada caotica", "spade caotiche", "f"),
 ("輝く爆竹槍", "shining bamboo spear"): ("lancia di bambù lucente", "lance di bambù lucenti", "f"),
 ("巨大な長針", "shining long hand"): ("lancetta lucente", "lancette lucenti", "f"),
 ("木の人形", "wooden doll"): ("bambola di legno", "bambole di legno", "f"),
 ("不審なエビフライ", "fried prawn"): ("gambero fritto", "gamberi fritti", "m"),
 ("光剣のような何か", "lightsabre-like thing"): ("affare simile a una spada laser", "affari simili a una spada laser", "m"),
 ("鮮やかな鋏鎌", "crab-scissors"): ("forbici da granchio", "forbici da granchio", "fp"),
 ("吹雪の苦無", "set of blizzard kunais"): ("kunai della bufera", "kunai della bufera", "mp"),
 ("稲妻の細剣", "lightning fleure"): ("fioretto fulminante", "fioretti fulminanti", "m"),
 ("空飛ぶ螺旋機", "flying drill"): ("trapano volante", "trapani volanti", "m"),
 ("長大な投斧", "double tomahawk"): ("tomahawk doppio", "tomahawk doppi", "m"),
 ("鋭い鋏鎌", "sharp scissors"): ("forbici affilate", "forbici affilate", "fp"),
 ("怪しい錫杖", "suspicious shakujo"): ("bastone monastico sospetto", "bastoni monastici sospetti", "m"),
 ("赤い節棍", "triple rod"): ("bastone a tre sezioni", "bastoni a tre sezioni", "m"),
 ("アンバランスな炎弩", "electro-ignition crossbow"): ("balestra a ignizione elettrica", "balestre a ignizione elettrica", "f"),
 ("異臭放つ靴下", "stinky sock"): ("calzino puzzolente", "calzini puzzolenti", "m"),
 ("狙撃用弩砲", "sniper ballista"): ("balista da cecchino", "baliste da cecchino", "f"),
 ("死臭纏う大岩", "boulder that reeks death"): ("masso che puzza di morte", "massi che puzzano di morte", "m"),
 ("毒噴きの連弩", "viper repeating bow"): ("balestra vipera a ripetizione", "balestre vipera a ripetizione", "f"),
 ("小さな弓", "tiny shortbow"): ("arco corto minuscolo", "archi corti minuscoli", "m"),
 ("固定器具", "anchor"): ("ancora", "ancore", "f"),
 ("ベルトだらけの服", "garb full of belts"): ("veste piena di cinghie", "vesti piene di cinghie", "f"),
 ("螺旋の指輪", "intertwined ring"): ("anello intrecciato", "anelli intrecciati", "m"),
 ("黒の粉砕球", "heavy crushing ball"): ("sfera frantumatrice pesante", "sfere frantumatrici pesanti", "f"),
 ("謎甲虫", "artificial beetle"): ("scarabeo artificiale", "scarabei artificiali", "m"),
 ("何かのチケット", "some kind of ticket"): ("biglietto misterioso", "biglietti misteriosi", "m"),
 ("神の呪玉", "cursed jewel of god"): ("gemma divina maledetta", "gemme divine maledette", "f"),
 ("金色の翼", "golden wing"): ("ala dorata", "ali dorate", "f"),
 ("神々しい宝石", "godly powers"): ("poteri divini", "poteri divini", "mp"),
 ("神の光玉", "god jewel"): ("sfera luminosa divina", "sfere luminose divine", "f"),
 ("盾冠", "crown shield"): ("scudo a corona", "scudi a corona", "m"),
 ("黒い鏡", "mirror shield"): ("scudo a specchio", "scudi a specchio", "m"),
 ("野花", "wild flower"): ("fiore selvatico", "fiori selvatici", "m"),
 ("風を割く戦斧", "wind-tearing war-axe"): ("ascia da guerra che fende il vento", "asce da guerra che fendono il vento", "f"),
 ("古びた鎌", "well-worn sickle"): ("falce consunta", "falci consunte", "f"),
 ("重いステッキ", "heavy stick"): ("bastone da passeggio pesante", "bastoni da passeggio pesanti", "m"),
 ("憎悪の骨弓", "skull bow of hatred"): ("arco d'ossa dell'odio", "archi d'ossa dell'odio", "m"),
 ("雷の蒼弓", "lightning bow"): ("arco fulminante", "archi fulminanti", "m"),
 ("属性の瞳", "colorful eyes"): ("occhi variopinti", "occhi variopinti", "mp"),
 ("ピンクの鎖鎌", "pink sickle"): ("falce rosa", "falci rosa", "f"),
 ("水晶球の首飾り", "necklace with crytal ball"): ("collana con sfera di cristallo", "collane con sfera di cristallo", "f"),
 ("白の革紐", "white leather straps"): ("cinghie di cuoio bianche", "cinghie di cuoio bianche", "fp"),
 ("紅魔の杖", "red rod"): ("bacchetta rossa", "bacchette rosse", "f"),
 ("シンダ ライオン", "dead lion"): ("leone morto", "leoni morti", "m"),
 ("大型機械副腕", "machine arms"): ("bracci meccanici", "bracci meccanici", "mp"),
 ("白鷹の剣", "white sword"): ("spada bianca", "spade bianche", "f"),
 ("音速の飛行箒", "supersonic magic broom"): ("scopa magica supersonica", "scope magiche supersoniche", "f"),
 ("いいパンツ", "hot pants"): ("mutande favolose", "mutande favolose", "fp"),
 ("光の戦輪", "shining ring"): ("cerchio lucente", "cerchi lucenti", "m"),
 ("多目的シャベル", "military shovel"): ("pala militare", "pale militari", "f"),
 ("蜃気楼の光子銃", "gun of mirage"): ("pistola del miraggio", "pistole del miraggio", "f"),
 ("黒い金砕棒", "rugged mace"): ("mazza rozza", "mazze rozze", "f"),
 ("血涙の鞭", "red whip"): ("frusta rossa", "fruste rosse", "f"),
 ("謎の機械兜", "machine helm"): ("elmo meccanico", "elmi meccanici", "m"),
 ("極北の銀鎧", "armor from Mayroon"): ("armatura di Mayroon", "armature di Mayroon", "f"),
 ("棘の鞭", "tingling whip"): ("frusta pungente", "fruste pungenti", "f"),
 ("心音の奏剣", "sword of melody"): ("spada della melodia", "spade della melodia", "f"),
 ("黄金の連接剣", "golden heavysword"): ("spadone dorato", "spadoni dorati", "m"),
 ("緑のオウムガイ", "green nautilus"): ("nautilo verde", "nautili verdi", "m"),
 ("対戦艦ライフル", "anti-materiel rifle"): ("fucile anti-materiale", "fucili anti-materiale", "m"),
 ("破壊の三叉戟", "trident of destruction"): ("tridente della distruzione", "tridenti della distruzione", "m"),
 ("怒涛の大太刀", "katana of raging power"): ("katana furiosa", "katana furiose", "f"),
 ("藍の爪", "blue claws"): ("artigli azzurri", "artigli azzurri", "mp"),
 ("石装飾の腰当", "power stone belt"): ("cintura di pietre", "cinture di pietre", "f"),
 ("魂の紬糸", "reincarnation"): ("reincarnazione", "reincarnazioni", "f"),
 ("黒い凶爪", "black claws"): ("artigli neri", "artigli neri", "mp"),
 ("星光の白鎌", "shining sickle"): ("falce lucente", "falci lucenti", "f"),
 ("闇を帯びた杖", "darkness staff"): ("bastone delle tenebre", "bastoni delle tenebre", "m"),
 ("特殊劣化スーツ", "white swimwear"): ("costume da bagno bianco", "costumi da bagno bianchi", "m"),
 ("特殊強化スーツ", "blue suit"): ("tuta blu", "tute blu", "f"),
 ("輝く羽ペン", "shining featherpen"): ("penna d'oca lucente", "penne d'oca lucenti", "f"),
 ("重力の手斧", "black handaxe"): ("ascia nera", "asce nere", "f"),
 ("竜鱗の棍", "blue rod"): ("bastone azzurro", "bastoni azzurri", "m"),
 ("音速の旋棍", "tonfa"): ("tonfa", "tonfa", "m"),
 ("斬撃の旋棍", "tonfa"): ("tonfa", "tonfa", "m"),
 ("連撃の旋棍", "tonfa"): ("tonfa", "tonfa", "m"),
 ("守護の旋棍", "tonfa"): ("tonfa", "tonfa", "m"),
 ("生贄の旋棍", "tonfa"): ("tonfa", "tonfa", "m"),
 ("有翼の幻銃", "Twin pistol"): ("pistola alata", "pistole alate", "f"),
 ("双生の銃", "twin pistol"): ("pistola gemella", "pistole gemelle", "f"),
 ("機械仕掛けの疑似餌", "machine lure"): ("esca meccanica", "esche meccaniche", "f"),
 ("金柄の月光剣", "shining sword"): ("spada lucente", "spade lucenti", "f"),
 ("小さな人形", "doll"): ("bambola", "bambole", "f"),
 ("青の霊薬", "blue color"): ("colore azzurro", "colori azzurri", "m"),
 ("タル詰めの神酒", "a barrel-size"): ("formato barile", "formati barile", "m"),
 ("制裁の水", "volatile reaction"): ("reazione volatile", "reazioni volatili", "f"),
 ("狂気の散弾銃", "auto shotgun"): ("fucile a pompa automatico", "fucili a pompa automatici", "m"),
 ("殺人ジョーカー", "joker"): ("jolly", "jolly", "m"),
 ("紺色の魔法帽", "deep blue hat"): ("cappello blu scuro", "cappelli blu scuro", "m"),
 ("謎の名刺", "business card"): ("biglietto da visita", "biglietti da visita", "m"),
 ("怪しい仮面", "stone mask"): ("maschera di pietra", "maschere di pietra", "f"),
 ("謎の笛", "black whistle"): ("fischietto nero", "fischietti neri", "m"),
 ("虹色の弓", "seven-colored greatbow"): ("grande arco dai sette colori", "grandi archi dai sette colori", "m"),
 ("閃光の機械弓", "rapid crossbow"): ("balestra rapida", "balestre rapide", "f"),
 ("一角獣の角槍", "black unicorn horn"): ("corno di unicorno nero", "corni di unicorno neri", "m"),
 ("新星榴弾", "nova grenade"): ("granata nova", "granate nova", "f"),
 ("アグニの宝剣", "fire sword"): ("spada di fuoco", "spade di fuoco", "f"),
 ("超硬度長ネギ", "ultrahard green onion"): ("cipollotto durissimo", "cipollotti durissimi", "m"),
 ("封印されし盾", "hard shield"): ("scudo resistente", "scudi resistenti", "m"),
 ("剛魔の杖", "shivering staff"): ("bastone tremante", "bastoni tremanti", "m"),
 ("呻く杖", "shivering staff"): ("bastone tremante", "bastoni tremanti", "m"),
 ("神の彫像", "deity of Irva"): ("divinità di Irva", "divinità di Irva", "f"),
 ("女神の彫像", "deity of Irva"): ("divinità di Irva", "divinità di Irva", "f"),
 ("艶やかな弦鈍器", "elegant string blunt"): ("arma a corde elegante", "armi a corde eleganti", "f"),
 ("巨大な十字手裏剣", "big shuriken"): ("shuriken grande", "shuriken grandi", "m"),
 ("勇気の刃", "brave knife"): ("lama del coraggio", "lame del coraggio", "f"),
 ("分厚い魔法書", "thick book"): ("libro spesso", "libri spessi", "m"),
 ("古の石貨", "big old coin"): ("grossa moneta antica", "grosse monete antiche", "f"),
 ("青のガントレット", "gauntlets of blue"): ("guanti d'arme azzurri", "guanti d'arme azzurri", "mp"),
 ("黒染めの忍刀", "black knife"): ("coltello nero", "coltelli neri", "m"),
 ("死神の狙撃銃", "sniper rifle of death"): ("fucile da cecchino della morte", "fucili da cecchino della morte", "m"),
 ("機械の翼", "metal wing"): ("ala di metallo", "ali di metallo", "f"),
 ("光のスティック", "radiant cane"): ("bastone radioso", "bastoni radiosi", "m"),
 ("巨大な十字剣", "big sword"): ("spada grande", "spade grandi", "f"),
 ("ド級の弩弓", "big crossbow"): ("balestra grande", "balestre grandi", "f"),
 ("重力榴弾銃", "gravity-grenade gun"): ("lanciagranate gravitazionale", "lanciagranate gravitazionali", "m"),
 ("鋼鉄の戦斧", "god axe"): ("ascia divina", "asce divine", "f"),
 ("獣の鎌", "gigantic claw"): ("artiglio gigantesco", "artigli giganteschi", "m"),
 ("よれよれの外套", "shabby cloak"): ("mantello sciatto", "mantelli sciatti", "m"),
 ("血塗れの包丁", "bloody knife"): ("coltello insanguinato", "coltelli insanguinati", "m"),
 ("水着風スーツ", "swimwear"): ("costume da bagno", "costumi da bagno", "m"),
 ("特別な飴玉", "special candy"): ("caramella speciale", "caramelle speciali", "f"),
 ("豪快なサーベル", "bold saber"): ("sciabola audace", "sciabole audaci", "f"),
 ("旧文明の貨幣", "old coin"): ("moneta antica", "monete antiche", "f"),
 ("多銃身回転式機関銃", "minigun"): ("mitragliatrice rotante", "mitragliatrici rotanti", "f"),
 ("神を裂く刃", "bloody edge"): ("lama insanguinata", "lame insanguinate", "f"),
 ("射突型パイル", "mechanical lance"): ("lancia meccanica", "lance meccaniche", "f"),
 ("両刃の大剣", "double-edged greatsword"): ("spadone a doppio taglio", "spadoni a doppio taglio", "m"),
 ("青いカプセル", "blue capsule"): ("capsula azzurra", "capsule azzurre", "f"),
 ("透明なポーション", "clear liquid"): ("liquido trasparente", "liquidi trasparenti", "m"),
 ("何の変哲もないピアノ", "nondescriptive piano"): ("pianoforte comune", "pianoforti comuni", "m"),
 ("名工の槌", "master hammer"): ("martello da maestro", "martelli da maestro", "m"),
 ("錆びた銃", "rusted pistol"): ("pistola arrugginita", "pistole arrugginite", "f"),
 ("角の生えた兜", "horned helmet"): ("elmo cornuto", "elmi cornuti", "m"),
 ("怪しい人物像", "a fishy figure"): ("figura sospetta", "figure sospette", "f"),
 ("見事な水晶", "beautiful stone"): ("cristallo splendido", "cristalli splendidi", "m"),
 ("謎のオブジェ", "unknown origin"): ("origine ignota", "origini ignote", "f"),
 ("謎の箱", "unknown content"): ("contenuto ignoto", "contenuti ignoti", "m"),
 ("謎の板切れ", "unknown origin"): ("origine ignota", "origini ignote", "f"),
 ("謎の紙切れ", "strange paper"): ("carta strana", "carte strane", "f"),
 ("赤い装飾の刀", "rutilant katana"): ("katana rossa", "katana rosse", "f"),
 ("美しい貝", "beautiful shell"): ("bella conchiglia", "belle conchiglie", "f"),
 ("猫の尻尾", "cat's tail"): ("coda di gatto", "code di gatto", "f"),
 ("ぼろぼろの紙切れ", "crumbling paper"): ("carta sbrindellata", "carte sbrindellate", "f"),
 ("赤い腰当", "red girdle"): ("cintura rossa", "cinture rosse", "f"),
 ("チクチクする盾", "tingling shield"): ("scudo pungente", "scudi pungenti", "m"),
 ("頑丈なリュート", "tough lute"): ("liuto robusto", "liuti robusti", "m"),
 ("頑丈なピアノ", "heavy piano"): ("pianoforte pesante", "pianoforti pesanti", "m"),
 ("黄色のネックレス", "yellow necklace"): ("collana gialla", "collane gialle", "f"),
 ("機械弓のネックレス", "purple necklace"): ("collana viola", "collane viola", "f"),
 ("粗野な剣", "brutish sword"): ("spada grezza", "spade grezze", "f"),
 ("かぐわしいぱんつ", "fragrant panties"): ("mutandine profumate", "mutandine profumate", "fp"),
 ("怪しい宝石", "strange jewel"): ("gemma sospetta", "gemme sospette", "f"),
 ("光る小石", "shining rock"): ("sasso lucente", "sassi lucenti", "m"),
 ("艶やかな弦楽器", "elegant string"): ("strumento a corde elegante", "strumenti a corde eleganti", "m"),
 ("うす汚れたペンダント", "dirty pendant"): ("ciondolo sporco", "ciondoli sporchi", "m"),
 ("ふわふわな尻尾", "fluffy tail"): ("coda soffice", "code soffici", "f"),
 ("機械仕掛けの球", "mechanical ball"): ("sfera meccanica", "sfere meccaniche", "f"),
 ("巨大な斧", "giant axe"): ("ascia gigantesca", "asce gigantesche", "f"),
 ("見たこともない機械", "freaky machine"): ("macchina mai vista", "macchine mai viste", "f"),
 ("エネルギー結晶体", "unknown mechanism"): ("meccanismo ignoto", "meccanismi ignoti", "m"),
 ("巨大な槌", "giant hammer"): ("martello gigantesco", "martelli giganteschi", "m"),
 ("細い短剣", "thin dagger"): ("pugnale sottile", "pugnali sottili", "m"),
 ("聖なる槍", "holy lance"): ("lancia sacra", "lance sacre", "f"),
 ("元素の魔杖", "elemental staff"): ("bastone elementale", "bastoni elementali", "m"),
 ("収穫の鎌", "harvest scythe"): ("falce del raccolto", "falci del raccolto", "f"),
 ("古の散弾銃", "ancient shotgun"): ("fucile a pompa antico", "fucili a pompa antichi", "m"),
 ("風をまとった長弓", "bow surrounded by wind"): ("arco avvolto dal vento", "archi avvolti dal vento", "m"),
 ("謎の宝石", "mysterious jewel"): ("gemma misteriosa", "gemme misteriose", "f"),
 ("とても危険な爆弾", "very dangerous bomb"): ("bomba molto pericolosa", "bombe molto pericolose", "f"),
 ("動いている心臓", "beating heart"): ("cuore che batte", "cuori che battono", "m"),
 ("見たこともない果物", "rare fruit"): ("frutto raro", "frutti rari", "m"),
 ("軽やかな靴", "light shoes"): ("scarpe leggere", "scarpe leggere", "fp"),
 ("不思議なチーズ", "mysterious cheese"): ("formaggio strano", "formaggi strani", "m"),
 ("冷たい仕掛け箱", "chilly box"): ("scatola fredda", "scatole fredde", "f"),
 ("不思議なリンゴ", "mysterious apple"): ("mela strana", "mele strane", "f"),
 ("透き通った鍵", "white key"): ("chiave bianca", "chiavi bianche", "f"),
 ("眩しい兜", "shining helm"): ("elmo abbagliante", "elmi abbaglianti", "m"),
 ("異国の門", "foreign gate"): ("portale straniero", "portali stranieri", "m"),
 ("金色のメダル", "golg coin"): ("medaglia dorata", "medaglie dorate", "f"),
 ("納税箱", "tax box"): ("cassetta delle tasse", "cassette delle tasse", "f"),
 ("いやな紙切れ", "lousy paper"): ("foglio sgradevole", "fogli sgradevoli", "m"),
 ("威圧感のある椅子", "glory chair"): ("poltrona imponente", "poltrone imponenti", "f"),
 ("足枷", "shakle"): ("ceppo", "ceppi", "m"),
 ("納入箱", "delivery chest"): ("baule delle consegne", "bauli delle consegne", "m"),
 ("虐殺の銃", "gun of genocide"): ("fucile del massacro", "fucili del massacro", "m"),
 ("アクアマリンの指輪", "blue ring"): ("anello azzurro", "anelli azzurri", "m"),
 ("地獄の槍斧", "cursed halberd"): ("alabarda maledetta", "alabarde maledette", "f"),
 ("鋼鉄の指輪", "steel ring"): ("anello d'acciaio", "anelli d'acciaio", "m"),
 ("血の滲むメイス", "bloody mace"): ("mazza insanguinata", "mazze insanguinate", "f"),
 ("燃える篭手", "burning gloves"): ("guanti d'arme ardenti", "guanti d'arme ardenti", "mp"),
 ("途方もない価値の金塊", "valuable gold bar"): ("lingotto d'oro di gran valore", "lingotti d'oro di gran valore", "m"),
 ("波動を放つ弓", "shaking bow"): ("arco vibrante", "archi vibranti", "m"),
 ("風をまとった短剣", "dagger surrounded by wind"): ("pugnale avvolto dal vento", "pugnali avvolti dal vento", "m"),
 ("全てを終結させる剣", "sword that ends all"): ("spada che tutto conclude", "spade che tutto concludono", "f"),
 ("死を奏でる大鎌", "scythe that sings death"): ("falce che canta la morte", "falci che cantano la morte", "f"),
 ("白銀の刀", "shining silver katana"): ("katana d'argento lucente", "katana d'argento lucenti", "f"),
 ("漆黒の剣", "pure black sword"): ("spada nerissima", "spade nerissime", "f"),
 ("バグの本", "book"): ("libro", "libri", "m"),
}
