# -*- coding: utf-8 -*-
"""Il resto del vocabolario degli epiteti: persone, astratti e qualita'.

La seconda meta' di [[epiteti_vocabolario]], che porta il vocabolario da 127
righe a tutte e 365. Sta in un file suo perche' le tre categorie qui dentro
sono quelle **astratte** — 人 le persone, 万能 il jolly che si accoppia con
tutto, 形 le qualita' — e chiedono scelte di registro che le categorie concrete
non chiedevano.

⚠️ **Il registro.** Gli epiteti di Elona sono volutamente sboccati: fra le 950
parole ci sono `bitch`, `whore`, `retard`, `gay`, `homo`, `pimp`. Il tono
volgare si tiene dove l'insulto e' generico — `bastard` → «bastardo», `idiot` →
«cretino», `airhead` → «testa vuota», `pimp` → «magnaccia» — ma le celle che
sono **slur identitari** restano **vuote**: 346 (`gay`/`homo`) per intero, e la
seconda meta' di 344 (`retard`) e di 161 (`whore`). Una cella vuota non e' una
dimenticanza: `random_title` la salta, quindi quelle parole semplicemente non
escono mai. E' la scelta che una localizzazione moderna fa di norma, ed e'
dichiarata qui invece di essere lasciata dedurre.

⚠️ **I doppioni si evitano a mano.** Il generatore accoppia due righe di
categoria diversa, ma **non guarda le parole**: se «traditore» sta a 136 e a
160, prima o poi esce «Traditore del traditore». Dove l'inglese ripete un
concetto in due righe, l'italiano prende un sinonimo: 160 `betrayer` diventa
«rinnegato», 176 `killer` diventa «omicida» perche' `assassin` gli sta accanto,
361 `knight` diventa «armigero» perche' «cavaliere» e' gia' a 92.
"""

# indice di riga -> ((nuda, preposizionale) colonna 0, idem colonna 1)
EXTRA = {
    # --- 人, le persone: le teste piu' usate del generatore --------------
    85: (("soldato", "del soldato"), ("guerriero", "del guerriero")),
    86: (("non morto", "del non morto"), ("morto", "del morto")),
    87: (("conte", "del conte"), ("visconte", "del visconte")),
    88: (("teschio", "del teschio"), ("scheletro", "dello scheletro")),
    89: (("spadaccino", "dello spadaccino"), ("gladiatore", "del gladiatore")),
    90: (("mercenario", "del mercenario"), ("buttafuori", "del buttafuori")),
    91: (("mago", "del mago"), ("stregone", "dello stregone")),
    92: (("cavaliere", "del cavaliere"), ("cavalleria", "della cavalleria")),
    93: (("alchimista", "dell'alchimista"), ("alchimia", "dell'alchimia")),
    94: (("angelo", "dell'angelo"), ("arcangelo", "dell'arcangelo")),
    95: (("apostolo", "dell'apostolo"), ("discepolo", "del discepolo")),
    96: (("medico", "del medico"), ("chirurgo", "del chirurgo")),
    97: (("sicario", "del sicario"), ("furfante", "del furfante")),
    98: (("rapinatore", "del rapinatore"), ("ladro", "del ladro")),
    99: (("sacerdote", "del sacerdote"), ("monaco", "del monaco")),
    100: (("prescelto", "del prescelto"), ("eletto", "dell'eletto")),
    101: (("campione", "del campione"), ("dominatore", "del dominatore")),
    102: (("saggio", "del saggio"), ("savio", "del savio")),
    103: (("avventuriero", "dell'avventuriero"), ("viandante", "del viandante")),
    104: (("fuggiasco", "del fuggiasco"), ("vagabondo", "del vagabondo")),
    105: (("malvagio", "del malvagio"), ("forestiero", "del forestiero")),
    106: (("poeta", "del poeta"), ("menestrello", "del menestrello")),
    107: (("lupo", "del lupo"), ("lupo d'argento", "del lupo d'argento")),
    108: (("leone", "del leone"), None),
    109: (("illusione", "dell'illusione"), ("illusionista", "dell'illusionista")),
    110: (("incantatore", "dell'incantatore"), None),
    111: (("ragazzo", "del ragazzo"), ("garzone", "del garzone")),
    112: (("ragazza", "della ragazza"), ("fanciulla", "della fanciulla")),
    113: (("anziano", "dell'anziano"), None),
    114: (("bambini", "dei bambini"), ("bambino", "del bambino")),
    115: (("neonato", "del neonato"), ("lattante", "del lattante")),
    116: (("cadavere", "del cadavere"), ("salma", "della salma")),
    117: (("drago", "del drago"), None),
    118: (("mostro", "del mostro"), ("demonio", "del demonio")),
    119: (("straniero", "dello straniero"), ("alieno", "dell'alieno")),
    120: (("pazzo", "del pazzo"), ("folle", "del folle")),
    121: (("genio", "del genio"), ("talento", "del talento")),
    122: (("dipendenza", "della dipendenza"), ("vizio", "del vizio")),
    123: (("cosa", "della cosa"), None),
    124: (("paziente", "del paziente"), None),
    125: (("amante", "dell'amante"), None),
    126: (("padre", "del padre"), ("genitori", "dei genitori")),
    127: (("madre", "della madre"), ("madonna", "della madonna")),
    128: (("fratello", "del fratello"), ("sorella", "della sorella")),
    129: (("figlio", "del figlio"), ("figlia", "della figlia")),
    130: (("fantasma", "del fantasma"), ("spettro", "dello spettro")),
    131: (("tigre", "della tigre"), ("tigre bianca", "della tigre bianca")),
    132: (("gigante", "del gigante"), None),
    133: (("belva", "della belva"), ("animale", "dell'animale")),
    134: (("pescatore", "del pescatore"), None),
    135: (("agitatore", "dell'agitatore"), ("ribellione", "della ribellione")),
    136: (("resistenza", "della resistenza"), ("traditore", "del traditore")),
    137: (("credente", "del credente"), ("seguace", "del seguace")),
    138: (("samurai", "del samurai"), ("ninja", "del ninja")),
    139: (("generale", "del generale"), ("istruttore", "dell'istruttore")),
    140: (("demone", "del demone"), ("diavolo", "del diavolo")),
    141: (("gatto", "del gatto"), ("gattino", "del gattino")),
    142: (("cane", "del cane"), ("cucciolo", "del cucciolo")),
    143: (("sparviero", "dello sparviero"), ("falcone", "del falcone")),
    144: (("combattente", "del combattente"), ("shogun", "dello shogun")),
    145: (("ingegno", "dell'ingegno"), None),
    146: (("tiratore", "del tiratore"), ("arciere", "dell'arciere")),
    147: (("sciocco", "dello sciocco"), ("buffone", "del buffone")),
    148: (("comandante", "del comandante"), ("maestro", "del maestro")),
    149: (("cercatore", "del cercatore"), ("ricerca", "della ricerca")),
    150: (("stratega", "dello stratega"), ("intrigante", "dell'intrigante")),
    151: (("buonuomo", "del buonuomo"), ("ipocrita", "dell'ipocrita")),
    152: (("empio", "dell'empio"), ("malfattore", "del malfattore")),
    153: (("vergine", "della vergine"), None),
    154: (("mano sinistra", "della mano sinistra"), ("mano destra", "della mano destra")),
    155: (("novellino", "del novellino"), ("nova", "della nova")),
    156: (("giocatore", "del giocatore"), ("azzardo", "dell'azzardo")),
    157: (("imbroglione", "dell'imbroglione"), ("truffatore", "del truffatore")),
    158: (("nobile", "del nobile"), None),
    159: (("servo", "del servo"), ("schiavo", "dello schiavo")),
    160: (("rinnegato", "del rinnegato"), ("delatore", "del delatore")),
    161: (("megera", "della megera"), None),          # ⚠️ `whore` resta vuota
    162: (("bellezza", "della bellezza"), ("dama", "della dama")),
    163: (("gentiluomo", "del gentiluomo"), ("damerino", "del damerino")),
    164: (("uomo", "dell'uomo"), ("umano", "dell'umano")),
    165: (("fante", "del fante"), ("compare", "del compare")),
    166: (("giudizio", "del giudizio"), ("sentenza", "della sentenza")),
    167: (("ubriacone", "dell'ubriacone"), ("beone", "del beone")),
    168: (("invasore", "dell'invasore"), ("intruso", "dell'intruso")),
    169: (("ragno", "del ragno"), None),
    170: (("eremita", "dell'eremita"), ("recluso", "del recluso")),
    171: (("salvatore", "del salvatore"), ("redentore", "del redentore")),
    172: (("maligno", "del maligno"), ("esorcista", "dell'esorcista")),
    173: (("artiglieria", "dell'artiglieria"), ("cecchino", "del cecchino")),
    174: (("professore", "del professore"), None),
    175: (("cane da caccia", "del cane da caccia"), ("segugio", "del segugio")),
    176: (("omicida", "dell'omicida"), ("assassino", "dell'assassino")),
    177: (("predone", "del predone"), ("saccheggiatore", "del saccheggiatore")),
    178: (("carnefice", "del carnefice"), None),
    179: (("incarnazione", "dell'incarnazione"), ("essenza", "dell'essenza")),
    180: (("nemico", "del nemico"), ("avversario", "dell'avversario")),
    181: (("protettore", "del protettore"), ("difensore", "del difensore")),
    182: (("guaritore", "del guaritore"), ("cura", "della cura")),
    183: (("compagno", "del compagno"), ("socio", "del socio")),
    184: (("eroe", "dell'eroe"), None),
    185: (("criminale", "del criminale"), ("peccatore", "del peccatore")),
    186: (("strega", "della strega"), ("maga", "della maga")),
    188: (("bambola", "della bambola"), ("burattino", "del burattino")),
    189: (("moglie", "della moglie"), ("marito", "del marito")),
    190: (("condottiero", "del condottiero"), ("artefice", "dell'artefice")),
    191: (("padrone", "del padrone"), ("esperto", "dell'esperto")),
    192: (("adepto", "dell'adepto"), None),
    193: (("capobanda", "del capobanda"), ("signore", "del signore")),
    338: (("testa vuota", "della testa vuota"), ("idiota", "dell'idiota")),
    339: (("bastardo", "del bastardo"), ("cretino", "del cretino")),
    340: (("uccello", "dell'uccello"), ("pulcino", "del pulcino")),
    342: (("amico", "dell'amico"), None),
    343: (("cincillà", "del cincillà"), ("svitato", "dello svitato")),
    344: (("tizio", "del tizio"), None),              # ⚠️ `retard` resta vuota
    # 346 (`gay` / `homo`) non compare affatto: resta tutta vuota
    347: (("piccione", "del piccione"), ("magnaccia", "del magnaccia")),
    349: (("borioso", "del borioso"), None),
    353: (("evocatore", "dell'evocatore"), ("druido", "del druido")),
    354: (("tagliagole", "del tagliagole"), ("attaccabrighe", "dell'attaccabrighe")),
    355: (("guardiano", "del guardiano"), ("giustiziere", "del giustiziere")),
    356: (("berserker", "del berserker"), ("brigante", "del brigante")),
    357: (("bandito", "del bandito"), ("negromante", "del negromante")),
    358: (("crociato", "del crociato"), ("paladino", "del paladino")),
    359: (("prete", "del prete"), ("chierico", "del chierico")),
    360: (("sciamano", "dello sciamano"), ("inquisitore", "dell'inquisitore")),
    361: (("custode", "del custode"), ("armigero", "dell'armigero")),
    362: (("borsaiolo", "del borsaiolo"), ("accolito", "dell'accolito")),
    363: (("tiratore scelto", "del tiratore scelto"), ("risanatore", "del risanatore")),
    # --- 万能, il jolly: e' l'unica categoria che si accoppia con se stessa
    275: (("lotta", "della lotta"), ("combattimento", "del combattimento")),
    276: (("cuore", "del cuore"), None),
    277: (("morte", "della morte"), ("fine", "della fine")),
    278: (("defunto", "del defunto"), ("epilogo", "dell'epilogo")),
    279: (("esito", "dell'esito"), None),
    280: (("dolore", "del dolore"), ("cicatrice", "della cicatrice")),
    281: (("fallimento", "del fallimento"), None),
    282: (("sconfitta", "della sconfitta"), ("perdente", "del perdente")),
    283: (("vittoria", "della vittoria"), ("trionfo", "del trionfo")),
    284: (("vincitore", "del vincitore"), ("vincente", "del vincente")),
    285: (("miracolo", "del miracolo"), ("prodigio", "del prodigio")),
    286: (("sorpresa", "della sorpresa"), None),
    287: (("macchina", "della macchina"), None),
    288: (("sacrificio", "del sacrificio"), None),
    289: (("racconto", "del racconto"), ("storia", "della storia")),
    290: (("baffi", "dei baffi"), None),
    291: (("magia", "della magia"), ("negromanzia", "della negromanzia")),
    292: (("corruzione", "della corruzione"), None),
    293: (("croce", "della croce"), None),
    294: (("giocattolo", "del giocattolo"), ("gioco", "del gioco")),
    295: (("sesso", "del sesso"), ("natura", "della natura")),
    296: (("perfezionista", "del perfezionista"), ("perfezione", "della perfezione")),
    297: (("immoralità", "dell'immoralità"), ("morale", "della morale")),
    298: (("secolo", "del secolo"), ("era", "dell'era")),
    299: (("inizio", "dell'inizio"), ("evo", "dell'evo")),
    300: (("origine", "dell'origine"), ("esordio", "dell'esordio")),
    301: (("catena", "della catena"), ("spirale", "della spirale")),
    302: (("elica", "dell'elica"), None),
    303: (("sangue", "del sangue"), ("emorragia", "dell'emorragia")),
    304: (("mondo", "del mondo"), None),
    305: (("comandamenti", "dei comandamenti"), None),
    306: (("rimembranza", "della rimembranza"), ("ricordo", "del ricordo")),
    307: (("memoria", "della memoria"), None),
    308: (("follia", "della follia"), ("demenza", "della demenza")),
    309: (("castigo", "del castigo"), ("colpa", "della colpa")),
    310: (("delitto", "del delitto"), ("peccato", "del peccato")),
    311: (("febbre", "della febbre"), None),
    312: (("gabbia", "della gabbia"), None),
    313: (("minaccia", "della minaccia"), ("pericolo", "del pericolo")),
    314: (("piacere", "del piacere"), ("edonista", "dell'edonista")),
    315: (("asso", "dell'asso"), ("attaccante", "dell'attaccante")),
    316: (("anello", "dell'anello"), ("collana", "della collana")),
    317: (("debolezza", "della debolezza"), None),
    318: (("istante", "dell'istante"), None),
    319: (("fusione", "della fusione"), None),
    320: (("lava", "della lava"), None),
    321: (("nebbia", "della nebbia"), ("bruma", "della bruma")),
    322: (("oblio", "dell'oblio"), ("perdita", "della perdita")),
    323: (("tempesta", "della tempesta"), ("portatempeste", "del portatempeste")),
    324: (("infinito", "dell'infinito"), ("ricorrenza", "della ricorrenza")),
    325: (("disastro", "del disastro"), ("calamità", "della calamità")),
    326: (("retaggio", "del retaggio"), ("eredità", "dell'eredità")),
    327: (("profondità", "della profondità"), ("abisso", "dell'abisso")),
    328: (("strage", "della strage"), ("massacro", "del massacro")),
    329: (("destino", "del destino"), ("fato", "del fato")),
    330: (("sorte", "della sorte"), None),
    331: (("fantasia", "della fantasia"), ("fantasmi", "dei fantasmi")),
    332: (("pugno", "del pugno"), ("profezia", "della profezia")),
    333: (("sentimento", "del sentimento"), ("profeta", "del profeta")),
    334: (("impurità", "dell'impurità"), ("macchia", "della macchia")),
    335: (("giustizia", "della giustizia"), None),
    336: (("marciume", "del marciume"), None),
    337: (("chioma", "della chioma"), None),
    341: (("bomba", "della bomba"), None),
    345: (("menzogna", "della menzogna"), None),
    350: (("pioggia", "della pioggia"), ("lacrima", "della lacrima")),
    351: (("deserto", "del deserto"), None),
    352: (("flusso", "del flusso"), None),
    # --- 形, le qualita' -------------------------------------------------
    15: (("rischio", "del rischio"), ("insidia", "dell'insidia")),
    18: (("unicità", "dell'unicità"), ("magnificenza", "della magnificenza")),
    19: (("dolcezza", "della dolcezza"), ("mitezza", "della mitezza")),
    20: (("tristezza", "della tristezza"), ("afflizione", "dell'afflizione")),
    21: (("vanità", "della vanità"), ("lutto", "del lutto")),
    22: (("diletto", "del diletto"), ("gioia", "della gioia")),
    23: (("odio", "dell'odio"), ("inimicizia", "dell'inimicizia")),
    26: (("grazia", "della grazia"), ("tesoro", "del tesoro")),
    28: (("capelli", "dei capelli"), None),
    29: (("quiete", "della quiete"), ("silenzio", "del silenzio")),
    32: (("paura", "della paura"), ("terrore", "del terrore")),
    33: (("tragedia", "della tragedia"), None),
    34: (("collera", "della collera"), ("furia", "della furia")),
    36: (("novità", "della novità"), ("freschezza", "della freschezza")),
    38: (("vigore", "del vigore"), ("energia", "dell'energia")),
    39: (("lucentezza", "della lucentezza"), ("bagliore", "del bagliore")),
    40: (("nome", "del nome"), None),
    41: (("vuoto", "del vuoto"), ("orgoglio", "dell'orgoglio")),
    42: (("unità", "dell'unità"), None),
    43: (("eleganza", "dell'eleganza"), ("leggiadria", "della leggiadria")),
    45: (("trascendenza", "della trascendenza"), ("superiorità", "della superiorità")),
    46: (("limite", "del limite"), None),
    47: (("freddezza", "della freddezza"), None),
    49: (("leggenda", "della leggenda"), ("mito", "del mito")),
    50: (("smarrimento", "dello smarrimento"), ("rinuncia", "della rinuncia")),
    53: (("speranza", "della speranza"), ("desiderio", "del desiderio")),
}
